name: Deploy Databricks Asset Bundle

on:
  push:
    branches:
      - main
    paths:
      - 'notebooks/**'
      - 'bundles/**'
      - 'databricks.yaml'

  workflow_dispatch:
    inputs:
      client_name:
        description: 'Client to deploy'
        required: true
      deploy_prefix:
        description: 'Prefix for all resource names (e.g. "tristar01_")'
        required: true

jobs:
  deploy-bundles:
    runs-on: ubuntu-latest

    # making DATABRICKS_HOST and DATABRICKS_TOKEN available to every step
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Installing the Databricks CLI v1 installer script
      - name: Install Databricks CLI v1
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | bash
          echo "$HOME/.databricks/bin" >> $GITHUB_PATH

      - name: Check/create client catalog (if missing)
        run: |
          databricks version

          # Storing the catalog name in a variable for readability
          CATALOG="${{ github.event.inputs.client_name }}"

          # Checking existence (positional arg), creating if absent
          if ! databricks catalogs get "$CATALOG" &> /dev/null; then
            echo "Catalog doesn’t exist. → creating…"
            databricks catalogs create "$CATALOG"
          else
            echo "Catalog already exists."
          fi

      - name: Deploy and Execute Bundle
        run: |
          # Deploying bundle using the provided inputs
          databricks bundle deploy --target dev \
            --var client_name="${{ github.event.inputs.client_name }}" \
            --var deploy_prefix="${{ github.event.inputs.deploy_prefix }}"

          # then running it
          databricks bundle run --target dev \
            clientparameter_gradient_dab_job \
            --var client_name="${{ github.event.inputs.client_name }}" \
            --var deploy_prefix="${{ github.event.inputs.deploy_prefix }}"
